services:
    postgres:
        image: postgres
        ports:
            - 5432:5432 #source:container
        environment:
            - POSTGRES_PASSWORD:example
            - POSTGRES_DB=mediasoup-video-stream